# Generated by Django 4.2.16 on 2024-10-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='indian_calendar/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanYourTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='plan_your_trip/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='state_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ThingsToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='things_to_do/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='popular',
        ),
        migrations.AddField(
            model_name='destination',
            name='airfare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='food_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FunPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fun_places_images/')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_places', to='home.state')),
            ],
        ),
        migrations.CreateModel(
            name='FamousFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='famous_foods_images/')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famous_foods', to='home.state')),
            ],
        ),
    ]
